# Generated by Django 2.2.5 on 2019-09-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookTypeObj',
            field=models.ForeignKey(db_column='bookTypeObj', on_delete=django.db.models.deletion.CASCADE, to='BookType.BookType', verbose_name='图书类别'),
        ),
    ]
